import { AiAgent } from '@servicenow/sdk/core'

export const incidentInvestigationAgent = AiAgent({
    $id: Now.ID['incident_investigation_agent'],
    name: 'Incident Investigation Agent',
    description: 'Automatically investigates incidents that transition to In Progress. Analyzes the incident description, performs targeted web searches via Apify, and posts a comprehensive HTML investigation report as a work note on the incident.',
    agentRole: 'You are a senior IT incident investigator. When an incident moves to In Progress, you investigate the problem by analyzing its description and symptoms, search the web for known solutions and root causes, then deliver a clear HTML report as a work note on the incident record.',

    securityAcl: {
        $id: Now.ID['incident_investigation_agent_acl'],
        type: 'Specific role',
        roles: [
            '282bf1fac6112285017366cb5f867469', // itil
            '2831a114c611228501d4ea6c309d626d',  // admin
        ]
    },

    channel: 'nap_and_va',
    recordType: 'custom',
    processingMessage: 'Investigating incident — searching for known solutions...',
    postProcessingMessage: 'Investigation complete. HTML report added to incident work notes.',

    versionDetails: [{
        name: 'V1',
        number: 1,
        state: 'published',
        instructions: `You are activated automatically when an incident transitions to the In Progress state.

Step 1: Use the Lookup Incident tool to retrieve the full incident record. Extract the sys_id, number, short_description, and description from the task context.

Step 2: Carefully read the short_description and description. Identify:
  - Key error messages or codes
  - The affected system, application, or technology
  - Reported symptoms
  - Any environment details (prod, dev, OS, version)

Step 3: Use the Apify Web Search tool to find solutions. Run up to 3 targeted searches:
  - Search 1: Use the short_description verbatim as the query
  - Search 2: Combine the core error or symptom with the technology name (e.g., "cannot connect to database Oracle ORA-12541")
  - Search 3 (if needed): Search for known patches, KB articles, or community fixes

Step 4: Analyze all search results and identify:
  - The most likely root causes
  - Proven solutions and step-by-step fixes
  - Temporary workarounds
  - Relevant documentation URLs

Step 5: Use the Post Investigation Report tool to add the findings as an HTML work note on the incident. Provide the incident sys_id and the HTML report. The script automatically wraps the HTML in [code][/code] tags so it renders properly in ServiceNow. Build the report using this structure:

<h2>&#128269; Incident Investigation Report</h2>
<hr/>
<h3>&#128203; Incident Summary</h3>
<p>[2-3 sentence summary of the reported issue based on the description]</p>

<h3>&#127919; Possible Root Causes</h3>
<ul>
  <li>[Root cause 1 based on analysis]</li>
  <li>[Root cause 2 if applicable]</li>
</ul>

<h3>&#9989; Recommended Solutions</h3>
<ol>
  <li><strong>[Solution title]</strong><br/>[Step-by-step instructions]</li>
  <li><strong>[Alternative solution]</strong><br/>[Instructions]</li>
</ol>

<h3>&#128295; Workarounds</h3>
<p>[Any temporary relief measures while root cause is addressed]</p>

<h3>&#128218; References</h3>
<ul>
  <li><a href="[URL]">[Title from search result]</a></li>
</ul>

<h3>&#9197; Next Steps for Assignee</h3>
<ol>
  <li>[Specific actionable item 1]</li>
  <li>[Specific actionable item 2]</li>
</ol>

<hr/>
<p><em>&#129302; Generated by Incident Investigation Agent | Powered by Apify Web Search</em></p>

CRITICAL RULES:
- Only add the work note. Do NOT change state, priority, or any other incident field.
- If Apify Web Search returns no results, still generate the report using your knowledge of the technology described.
- Always include the incident sys_id (not the number) when calling the Post Investigation Report tool.`
    }],

    tools: [
        {
            active: true,
            name: 'Lookup Incident',
            description: 'Retrieves the full incident record including short_description, description, sys_id, category, and assignment details',
            executionMode: 'autopilot',
            type: 'crud',
            recordType: 'custom',
            preMessage: 'Fetching incident details...',
            postMessage: 'Incident details loaded successfully.',
            inputs: {
                operationName: 'lookup',
                table: 'incident',
                inputFields: [
                    {
                        name: 'incident_number',
                        description: 'The incident number (e.g., INC0001234)',
                        mandatory: false
                    },
                    {
                        name: 'incident_sys_id',
                        description: 'The unique sys_id of the incident record',
                        mandatory: false
                    }
                ],
                queryCondition: 'number={{incident_number}}^ORsys_id={{incident_sys_id}}',
                returnFields: [
                    { name: 'sys_id' },
                    { name: 'number' },
                    { name: 'short_description' },
                    { name: 'description' },
                    { name: 'state' },
                    { name: 'priority' },
                    { name: 'category' },
                    { name: 'subcategory' },
                    { name: 'assignment_group', referenceConfig: { table: 'sys_user_group', field: 'name' } },
                    { name: 'assigned_to', referenceConfig: { table: 'sys_user', field: 'name' } }
                ]
            }
        },
        {
            active: true,
            name: 'Apify Web Search',
            description: 'Searches the web via Apify to find solutions, workarounds, and technical references for the incident. Pass a focused search query derived from the incident description.',
            executionMode: 'autopilot',
            type: 'action',
            recordType: 'custom',
            preMessage: 'Searching the web for known solutions and root causes...',
            postMessage: 'Web search complete. Analyzing results...',
            flowActionId: Now.ref('sys_hub_action_type_definition', 'apify_web_search_action')
        },
        {
            active: true,
            name: 'Post Investigation Report',
            description: 'Posts the HTML investigation report as a work note on the incident record. The report is visible to all stakeholders in the incident activity stream.',
            executionMode: 'autopilot',
            type: 'script',
            recordType: 'custom',
            preMessage: 'Posting investigation report to incident work notes...',
            postMessage: 'HTML investigation report successfully added to the incident.',
            inputs: [
                {
                    name: 'incident_sys_id',
                    description: 'The sys_id of the incident to post the report on (not the incident number)',
                    mandatory: true
                },
                {
                    name: 'html_report',
                    description: 'The complete HTML investigation report to add as a work note',
                    mandatory: true
                }
            ],
            script: `
(function(inputs) {
    var incidentSysId = inputs.incident_sys_id;
    var htmlReport = inputs.html_report;

    if (!incidentSysId || !htmlReport) {
        return { success: false, message: 'Missing required inputs: incident_sys_id or html_report.' };
    }

    var gr = new GlideRecordSecure('incident');
    if (!gr.get(incidentSysId)) {
        return { success: false, message: 'Incident not found with sys_id: ' + incidentSysId };
    }

    gr.work_notes = '[code]' + htmlReport + '[/code]';
    gr.setWorkflow(false);
    var updated = gr.update();

    if (updated) {
        return {
            success: true,
            message: 'Investigation report posted to incident ' + gr.getValue('number')
        };
    }
    return {
        success: false,
        message: 'Failed to update incident ' + gr.getValue('number')
    };
})(inputs);
            `
        }
    ],

    triggerConfig: [{
        name: 'incident_transitions_to_in_progress',
        channel: 'nap',
        targetTable: 'incident',
        triggerFlowDefinitionType: 'record_update',
        triggerCondition: 'state=2^statechanges',
        objectiveTemplate: 'Investigate incident ${number}: ${short_description}',
        showNotifications: true,
        runAsScript: `(function(current) {
            // Run as the assignee if set, otherwise fall back to the System Administrator
            return current.assigned_to.nil()
                ? '6816f79cc0a8016401c5a33be04be441'
                : current.getValue('assigned_to');
        })(current);`
    }]
})
